apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
     color: red
     app: red-app 
spec:
  containers:
    - name: red
      image: janakiramm/color
      env: 
      - name: "COLOR"
        value: "red"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: green
  labels:
     color: green
     app: green-app 
spec:
  containers:
    - name: green
      image: janakiramm/color
      env: 
      - name: "COLOR"
        value: "green"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: blue
  labels:
     color: blue
     app: blue-app 
spec:
  containers:
    - name: blue
      image: janakiramm/color
      env: 
      - name: "COLOR"
        value: "blue"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP