apiVersion: v1
kind: Service
metadata:
  name: red
spec:
  selector:
    app: red-app
    color: red
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    nodePort: 31001
    port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  selector:
    app: green-app
    color: green
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    nodePort: 31002
    port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  selector:
    app: blue-app
    color: blue
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    nodePort: 31003
    port: 80
    targetPort: 8080