apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    nodePort: 31005
    port: 80
    targetPort: 3000