apiVersion: v1
kind: Service
metadata:
  name: db
  labels: 
    app: todoapp
    name: mongo
spec:
  selector:
    name: mongo
  type: ClusterIP
  ports:
  - protocol: TCP
    name: db
    port: 27017
    targetPort: 27017