apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
     type: local
spec:
  capacity:
     storage: 1Gi
  accesModes:
    - ReadWriteOnce
  peristentVolumeReclaimPolicy: recycle
  nfs: 
    path: /opt/data/web
    server: 10.51.58.238