apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     env: dev
     app: nginx-app 
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: "http-server"
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: my-vol
          mountPath: /usr/share/nginx/html
  volumes:
   - name: my-vol
     persistentVolumeClaim:
       claimName: my-pvc