apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
     name: web
     app: demo
     env: QA
spec:
  replicas: 10
  template:
    metadata:
      labels:
         name: web
    spec: 
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP