apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-web
  labels:
     name: mongo-web
     app: todoapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
         name: mongo-web
    spec: 
      containers:
        - name: mongo-web
          image: janakiramm/todo-app
          env:
           - name: mongo-web
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP