apiVersion: v1
kind: Pod
metadata:
  name: mongo-web
  labels:
     app: todoapp
     name: mongo-web
spec:
  containers:
    - name: my-mongo-web
      image: janakiramm/todo-app
      ports:
        - name: http
          containerPort: 3000
          protocol: TCP